[package]
name = "resumecompiler"
version = "1.0.3"
description = "A compiler that compiles Markdown files into a resume PDF file, formatted in LaTeX."
authors = ["raphaellith"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix makes the lib name unique and avoids conflicts with the bin name.
name = "resumecompiler_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
